version: "3"

services:
  db:
    image: mysql:8.0
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci --default-authentication-plugin=mysql_native_password
    environment:
      LANG: C.UTF-8
      TZ: Asia/Tokyo
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: dev
    volumes:
      - ./volume_db:/var/lib/mysql
    ports:
      - "3306:3306"

  front:
    build: ./front
    environment:
      TZ: Asia/Tokyo
    volumes:
      - ./front:/vue_app
      - ~/.bashrc:/root/.bashrc:ro
      - ~/.bash_profile:/etc/profile:ro
    # command: yarn serve
    command: /bin/ash
    tty: true
    depends_on:
      - back
    ports:
      - 8080:8080

  back:
    build: ./back
    environment:
      TZ: Asia/Tokyo
    volumes:
      - ./back:/rails_app
      - ~/.bashrc:/root/.bashrc:ro
      - ~/.bash_profile:/etc/profile:ro
    # command: bundle exec puma -C config/puma.rb
    # command: rails s -p 3000 -b '0.0.0.0'
    command: /bin/ash
    tty: true
    depends_on:
      - db
    ports:
      - 3000:3000
    links:
      - db

  web:
    build: ./web
    volumes:
      - ./back:/rails_app
      - ./web/nginx.conf:/etc/nginx/conf.d/webapp.conf
    ports:
      - 80:80
    depends_on:
      - back
    links:
      - back

volumes:
  volume-db:
